# Set env variables if you want to configure

# APT_INSTALL
# SETARCH
# ASAN

PATCH_OPENSSL=${PATCH_OPENSSL:=0}

OPENSSL_BRANCH=${OPENSSL_BRANCH:=master}
OPENSSL_INSTALL_PREFIX=${OPENSSL_INSTALL_PREFIX:=$HOME/opt}
# OPENSSL_USE_RPATH